language: ruby

rvm:
  - 2.2.1

script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:seed
  - bundle exec rspec spec/

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/air.yml.example config/air.yml
